### ISSUE TITLE
Checkboxes doesnt check with click

### ISSUE THREAD

**Issue by ogaleac** [jcdevelopmentspain/Test-Generator-Chrome-Extension#1]
Hi there !

I have an issue with the extension:
When I open the devtools tab, elements in the HTML doesnt work as they should.
For example, checkboxes doesnt change their status with click interaction.

¿There's any way to avoid this?

Thank u

Oscar

**Comment by jcdevelopmentspain** [comment]
Hi !

Thank you so much for your time.

As you said, some HTML elements didn't work as they should when the extension was working.
This happened because the extensions started at the time you open the devtools panel. We've solved this with the v1.2.0 and now the extension only runs when its tab is opened.

Hope you find this helpful for your experience :)
